name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22999
          script: |
            cd /home/pndmddgq/repositories/supraorigin
            git pull origin main
            cp -R * /home/pndmddgq/public_html/
            rm -f /home/pndmddgq/public_html/.cpanel.yml
            rm -f /home/pndmddgq/public_html/README.md
            echo "Deployed successfully!"